# Generated by Django 2.2 on 2022-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField()),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('views_count', models.IntegerField(default=0, verbose_name='количетсов просмотров')),
            ],
            options={
                'db_table': 'advertisements',
            },
        ),
    ]
