# Generated by Django 2.2 on 2022-11-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.AuthorInformation'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='heading',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.Headings'),
        ),
    ]
