# Generated by Django 2.2 on 2022-11-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20221128_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.AuthorInformation', verbose_name='автор объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ended_at',
            field=models.DateTimeField(null=True, verbose_name='дата окончания объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='heading',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.Headings', verbose_name='рубрика'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='authorinformation',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='authorinformation',
            name='phone_number',
            field=models.CharField(max_length=1000, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='headings',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='название рубрики'),
        ),
    ]
